# Generated by Django 3.0.7 on 2020-07-04 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20200703_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='cate',
        ),
    ]
