# Generated by Django 3.0.7 on 2020-07-05 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20200705_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday',
            new_name='date_birthday',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cate',
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.Category', verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta'),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
        migrations.AlterModelTable(
            name='detsale',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sale',
            table=None,
        ),
    ]
